// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbHc0Bs2A6F9nxs0IvG9YhcOMq_yWn6eo',
    appId: '1:494739822406:web:441c6238fa98c10857f747',
    messagingSenderId: '494739822406',
    projectId: 'wasl-b40ae',
    authDomain: 'wasl-b40ae.firebaseapp.com',
    storageBucket: 'wasl-b40ae.appspot.com',
    measurementId: 'G-QJK6Z9XVTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxhYgeMi42UrvakwhQk1XZgUcLlGRrsUI',
    appId: '1:494739822406:android:6b7e8c4f90daa79957f747',
    messagingSenderId: '494739822406',
    projectId: 'wasl-b40ae',
    storageBucket: 'wasl-b40ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYVPJpMoiNRhRHGmI2ANj2G8FdOZsLeTM',
    appId: '1:494739822406:ios:8b71f1f8bbf7820257f747',
    messagingSenderId: '494739822406',
    projectId: 'wasl-b40ae',
    storageBucket: 'wasl-b40ae.appspot.com',
    iosBundleId: 'com.example.wasl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYVPJpMoiNRhRHGmI2ANj2G8FdOZsLeTM',
    appId: '1:494739822406:ios:8b71f1f8bbf7820257f747',
    messagingSenderId: '494739822406',
    projectId: 'wasl-b40ae',
    storageBucket: 'wasl-b40ae.appspot.com',
    iosBundleId: 'com.example.wasl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbHc0Bs2A6F9nxs0IvG9YhcOMq_yWn6eo',
    appId: '1:494739822406:web:54dfef0e3225e9e457f747',
    messagingSenderId: '494739822406',
    projectId: 'wasl-b40ae',
    authDomain: 'wasl-b40ae.firebaseapp.com',
    storageBucket: 'wasl-b40ae.appspot.com',
    measurementId: 'G-3QTSFS26J9',
  );
}
