# يمكنك تحديد نسخة iOS المستهدفة هنا
platform :ios, '13.0'

# ignore_all_warnings!  # يمكنك استخدام هذا السطر لتجاهل التحذيرات إذا كنت تواجه تحذيرات كثيرة

# إعداد المكتبات (Pods) الخاصة بمشروعك
target 'Runner' do
  use_frameworks!
  use_modular_headers!

end
